name: 'Check package access in organisation'
description: 'Check package access in organisation'
inputs:
  organisation:  # name of organisation in all lowercase
    description: 'Name of the organisation'
    required: true
  include-current-repo:  # whether to include the current repo in the check
    description: 'Whether to include the current repo in the check'
    required: false
    default: 'false'
  personal-access-token: #if using a personal access token (PAT), set it here
    description: 'Personal access token from GitHub'
    required: false
outputs:
  has-access-to-packages: # whether the user has access to packages
    description: 'Whether the user has access to packages'
runs:
  using: 'node20'
  main: 'index.js'
